export const FETCH_DATA = "FETCH_DATA";
export const ADD_DATA = "ADD_DATA";
export const UPDATE_DATA = "UPDATE_DATA";
export const DELETE_DATA = "DELETE_DATA";

// Quản lý kho
export const FETCH_NHAPKHOTHUOC = "FETCH_NHAPKHOTHUOC";
export const DELETE_NHAPKHOTHUOC = "DELETE_NHAPKHOTHUOC";
export const CREATE_NHAPKHOTHUOC = "CREATE_NHAPKHOTHUOC";
export const EDIT_NHAPKHOTHUOC = "EDIT_NHAPKHOTHUOC";
export const UPDATE_NHAPKHOTHUOC = "UPDATE_NHAPKHOTHUOC";

// Quản lý nhà files
export const FETCH_FILES = "FETCH_FILES";
export const DELETE_FILES = "DELETE_FILES";
export const CREATE_FILES = "CREATE_FILES";
export const EDIT_FILES = "EDIT_FILES";
export const UPDATE_FILES = "UPDATE_FILES";

// Quản lý nhà cung cấp
export const FETCH_NHACUNGCAP = "FETCH_NHACUNGCAP";
export const DELETE_NHACUNGCAP = "DELETE_NHACUNGCAP";
export const CREATE_NHACUNGCAP = "CREATE_NHACUNGCAP";
export const EDIT_NHACUNGCAP = "EDIT_NHACUNGCAP";
export const UPDATE_NHACUNGCAP = "UPDATE_NHACUNGCAP";
export const FETCH_NHACUNGCAP_SELECT = "FETCH_NHACUNGCAP_SELECT";

// Quản lý thông tin khách hàng
export const FETCH_THONGTINKHACHHANG = "FETCH_THONGTINKHACHHANG";
export const DELETE_THONGTINKHACHHANG = "DELETE_THONGTINKHACHHANG";
export const CREATE_THONGTINKHACHHANG = "CREATE_THONGTINKHACHHANG";
export const EDIT_THONGTINKHACHHANG = "EDIT_THONGTINKHACHHANG";
export const UPDATE_THONGTINKHACHHANG = "UPDATE_THONGTINKHACHHANG";

// Quản lý bán hàng
export const FETCH_BANHANG = "FETCH_BANHANG";
export const DELETE_BANHANG = "DELETE_BANHANG";
export const CREATE_BANHANG = "CREATE_BANHANG";
export const EDIT_BANHANG = "EDIT_BANHANG";
export const UPDATE_BANHANG = "UPDATE_BANHANG";
export const ITEM_HOADON_BANHANG = "ITEM_HOADON_BANHANG";

// Quản lý hoá đơn đã hoàn thất
export const FETCH_HOADONDAHOANTAT = "FETCH_HOADONDAHOANTAT";
export const FETCH_LICHSUHOADON = "FETCH_LICHSUHOADON";
export const DELETE_HOADONDAHOANTAT = "DELETE_HOADONDAHOANTAT";
export const CREATE_HOADONDAHOANTAT = "CREATE_HOADONDAHOANTAT";
export const EDIT_HOADONDAHOANTAT = "EDIT_HOADONDAHOANTAT";
export const UPDATE_HOADONDAHOANTAT = "UPDATE_HOADONDAHOANTAT";
export const HOADONDAHOANTAT_THEO_KHACHHANG = "HOADONDAHOANTAT_THEO_KHACHHANG";

// Quản lý user
export const FETCH_TAIKHOAN = "FETCH_TAIKHOAN";
export const DELETE_TAIKHOAN = "DELETE_TAIKHOAN";
export const CREATE_TAIKHOAN = "CREATE_TAIKHOAN";
export const EDIT_TAIKHOAN = "EDIT_TAIKHOAN";
export const UPDATE_TAIKHOAN = "UPDATE_TAIKHOAN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

//Quan lý thông báo
export const FETCH_THONGBAO = "FETCH_THONGBAO";
export const DELETE_THONGBAO = "DELETE_THONGBAO";

//QuanLyCMND

export const FETCH_CMND = "FETCH_CMND";
export const CREATE_CMND = "CREATE_CMND";
export const DELETE_CMND = "DELETE_CMND";

// Quản lý Hoá đơn GTGT
export const FETCH_HOADON_GTGT = "FETCH_HOADON_GTGT";
export const DELETE_HOADON_GTGT = "DELETE_HOADON_GTGT";
export const CREATE_HOADON_GTGT = "CREATE_HOADON_GTGT";
export const EDIT_HOADON_GTGT = "EDIT_HOADON_GTGT";
export const UPDATE_HOADON_GTGT = "UPDATE_HOADON_GTGT";

//QuanLyCMND

export const FETCH_CRUD = "FETCH_CRUD";
export const CREATE_CRUD = "CREATE_CRUD";
export const DELETE_CRUD = "DELETE_CRUD";
export const EDIT_CRUD = "EDIT_CRUD";
export const UPDATE_CRUD = "UPDATE_CRUD";
export const SELECT_CRUD = "SELECT_CRUD";
export const PAGE_PAGINATION = "PAGE_PAGINATION";

// Quaả ly tin tức

export const FETCH_TINTUC = "FETCH_TINTUC";
export const FETCH_TINTUC_TONGHOP = "FETCH_TINTUC_TONGHOP";
export const CREATE_TINTUC = "CREATE_TINTUC";
export const DELETE_TINTUC = "DELETE_TINTUC";
export const EDIT_TINTUC = "EDIT_TINTUC";
export const LIST_TAG = "LIST_TAG";
export const UPDATE_TINTUC = "UPDATE_TINTUC";
export const SELECT_TINTUC = "SELECT_TINTUC";

//Banner
export const BANNER_LEFT = "BANNER_LEFT";
export const BANNER_FOOTER = "BANNER_FOOTER";
export const BANNER_TONGHOP = "BANNER_TONGHOP";
export const BANNER_BY_TAG = "BANNER_BY_TAG";
export const BANNER_BOTTOM = "BANNER_BOTTOM";
export const BANNER_TOP = "BANNER_TOP";
export const BANNER_SLIDE = "BANNER_SLIDE";

// Quyen
export const FETCH_QUYEN = "FETCH_QUYEN";
export const FETCH_MENU_ITEM = "FETCH_MENU_ITEM";

// render menu
export const DUYET_BAI = "DUYET_BAI";
export const DEFAULT = "DEFAULT";
export const THEM_CHUC_NANG_DUYET_BAI_VAO_DEFAULT =
  "THEM_CHUC_NANG_DUYET_BAI_VAO_DEFAULT";
export const THEM_CHUC_NANG_TRA_LOI_DONG_GOP_DEFAULT =
  "THEM_CHUC_NANG_TRA_LOI_DONG_GOP_DEFAULT";

// SEARCH
export const SEARCH_CRUD_AUTO = "SEARCH_CRUD_AUTO";
export const SEARCH_BAI_VIET = "SEARCH_BAI_VIET";
